export const REGISTER_USER = "REGISTER_USER"
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL"
export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL"
export const USER_PROFILE = "USER_PROFILE"
export const USER_PROFILE_FAIL = "USER_PROFILE_FAIL"




export const ADD_HOTEL = "ADD_HOTEL"
export const ADD_HOTEL_FAIL = "ADD_HOTEL_FAIL"
export const GET_HOTEL_BY_ID = "GET_HOTEL_BY_ID"
export const GET_HOTEL_BY_ID_FAIL = "GET_HOTEL_BY_ID_FAIL"
export const ALL_HOTELS = "ALL_HOTELS"
export const ALL_HOTELS_FAIL = 'ALL_HOTELS_FAIL'
